# Generated by Django 3.2.7 on 2021-10-08 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('abstract', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.CharField(blank=True, max_length=500, null=True)),
                ('downloads', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
