# Generated by Django 3.2.7 on 2021-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
