# Generated by Django 3.2.7 on 2021-11-07 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_paper_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('step', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('pre_proposal', 'PRE-PROPOSAL'), ('proposal', 'PROPOSAL'), ('colloquium', 'COLLOQUIUM'), ('final_oral', 'FINAL-ORAL')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
