# Generated by Django 3.2.7 on 2021-11-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20211108_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='progress',
            field=models.BooleanField(default=False),
        ),
    ]
