# Generated by Django 3.2.7 on 2021-11-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_portal_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='progress',
            new_name='completed',
        ),
    ]
