# Generated by Django 3.2.7 on 2021-11-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_rename_progress_portal_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='stage',
            field=models.CharField(choices=[('Pre-Proposal', 'PRE-PROPOSAL'), ('Proposal', 'PROPOSAL'), ('Research Colloquium', 'COLLOQUIUM'), ('Final Oral Defense', 'FINAL-ORAL')], max_length=20),
        ),
    ]
